version: '3'
services:
  jenkins:
    image: jenkins
    ports:
    - "8080:8080"
    - "50000:50000"
    volumes:
    - ./jenkins_home:/var/jenkins_home
  prometheus:
    image: prom/prometheus
    ports:
    - "9090:9090"
    volumes:
    - ./prometheus/prometheus.yml:/etc/prometheus/prometheus.yml
